// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/dataproc/v1beta2/operations.proto

#include "google/cloud/dataproc/v1beta2/operations.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ClusterOperationMetadata_LabelsEntry_DoNotUse;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_ClusterOperationStatus;
}  // namespace protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto
namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_google_2fprotobuf_2ftimestamp_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Timestamp;
}  // namespace protobuf_google_2fprotobuf_2ftimestamp_2eproto
namespace google {
namespace cloud {
namespace dataproc {
namespace v1beta2 {
class ClusterOperationStatusDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClusterOperationStatus>
      _instance;
} _ClusterOperationStatus_default_instance_;
class ClusterOperationMetadata_LabelsEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClusterOperationMetadata_LabelsEntry_DoNotUse>
      _instance;
} _ClusterOperationMetadata_LabelsEntry_DoNotUse_default_instance_;
class ClusterOperationMetadataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ClusterOperationMetadata>
      _instance;
} _ClusterOperationMetadata_default_instance_;
}  // namespace v1beta2
}  // namespace dataproc
}  // namespace cloud
}  // namespace google
namespace protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto {
static void InitDefaultsClusterOperationStatus() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::cloud::dataproc::v1beta2::_ClusterOperationStatus_default_instance_;
    new (ptr) ::google::cloud::dataproc::v1beta2::ClusterOperationStatus();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::cloud::dataproc::v1beta2::ClusterOperationStatus::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ClusterOperationStatus =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsClusterOperationStatus}, {
      &protobuf_google_2fprotobuf_2ftimestamp_2eproto::scc_info_Timestamp.base,}};

static void InitDefaultsClusterOperationMetadata_LabelsEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::cloud::dataproc::v1beta2::_ClusterOperationMetadata_LabelsEntry_DoNotUse_default_instance_;
    new (ptr) ::google::cloud::dataproc::v1beta2::ClusterOperationMetadata_LabelsEntry_DoNotUse();
  }
  ::google::cloud::dataproc::v1beta2::ClusterOperationMetadata_LabelsEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ClusterOperationMetadata_LabelsEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsClusterOperationMetadata_LabelsEntry_DoNotUse}, {}};

static void InitDefaultsClusterOperationMetadata() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::cloud::dataproc::v1beta2::_ClusterOperationMetadata_default_instance_;
    new (ptr) ::google::cloud::dataproc::v1beta2::ClusterOperationMetadata();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::cloud::dataproc::v1beta2::ClusterOperationMetadata::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_ClusterOperationMetadata =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsClusterOperationMetadata}, {
      &protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::scc_info_ClusterOperationStatus.base,
      &protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::scc_info_ClusterOperationMetadata_LabelsEntry_DoNotUse.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ClusterOperationStatus.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ClusterOperationMetadata_LabelsEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ClusterOperationMetadata.base);
}

::google::protobuf::Metadata file_level_metadata[3];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationStatus, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationStatus, state_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationStatus, inner_state_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationStatus, details_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationStatus, state_start_time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata_LabelsEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata_LabelsEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata_LabelsEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata_LabelsEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata, cluster_name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata, cluster_uuid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata, status_history_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata, operation_type_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata, description_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata, labels_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata, warnings_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::google::cloud::dataproc::v1beta2::ClusterOperationStatus)},
  { 9, 16, sizeof(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata_LabelsEntry_DoNotUse)},
  { 18, -1, sizeof(::google::cloud::dataproc::v1beta2::ClusterOperationMetadata)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::cloud::dataproc::v1beta2::_ClusterOperationStatus_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::cloud::dataproc::v1beta2::_ClusterOperationMetadata_LabelsEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::cloud::dataproc::v1beta2::_ClusterOperationMetadata_default_instance_),
};

static void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "google/cloud/dataproc/v1beta2/operations.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, file_level_enum_descriptors, NULL);
}

static void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 3);
}

static void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n.google/cloud/dataproc/v1beta2/operatio"
      "ns.proto\022\035google.cloud.dataproc.v1beta2\032"
      "\034google/api/annotations.proto\032\037google/pr"
      "otobuf/timestamp.proto\"\372\001\n\026ClusterOperat"
      "ionStatus\022J\n\005state\030\001 \001(\0162;.google.cloud."
      "dataproc.v1beta2.ClusterOperationStatus."
      "State\022\023\n\013inner_state\030\002 \001(\t\022\017\n\007details\030\003 "
      "\001(\t\0224\n\020state_start_time\030\004 \001(\0132\032.google.p"
      "rotobuf.Timestamp\"8\n\005State\022\013\n\007UNKNOWN\020\000\022"
      "\013\n\007PENDING\020\001\022\013\n\007RUNNING\020\002\022\010\n\004DONE\020\003\"\237\003\n\030"
      "ClusterOperationMetadata\022\024\n\014cluster_name"
      "\030\007 \001(\t\022\024\n\014cluster_uuid\030\010 \001(\t\022E\n\006status\030\t"
      " \001(\01325.google.cloud.dataproc.v1beta2.Clu"
      "sterOperationStatus\022M\n\016status_history\030\n "
      "\003(\01325.google.cloud.dataproc.v1beta2.Clus"
      "terOperationStatus\022\026\n\016operation_type\030\013 \001"
      "(\t\022\023\n\013description\030\014 \001(\t\022S\n\006labels\030\r \003(\0132"
      "C.google.cloud.dataproc.v1beta2.ClusterO"
      "perationMetadata.LabelsEntry\022\020\n\010warnings"
      "\030\016 \003(\t\032-\n\013LabelsEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005va"
      "lue\030\002 \001(\t:\0028\001B}\n!com.google.cloud.datapr"
      "oc.v1beta2B\017OperationsProtoP\001ZEgoogle.go"
      "lang.org/genproto/googleapis/cloud/datap"
      "roc/v1beta2;dataprocb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 948);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "google/cloud/dataproc/v1beta2/operations.proto", &protobuf_RegisterTypes);
  ::protobuf_google_2fapi_2fannotations_2eproto::AddDescriptors();
  ::protobuf_google_2fprotobuf_2ftimestamp_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto
namespace google {
namespace cloud {
namespace dataproc {
namespace v1beta2 {
const ::google::protobuf::EnumDescriptor* ClusterOperationStatus_State_descriptor() {
  protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::file_level_enum_descriptors[0];
}
bool ClusterOperationStatus_State_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const ClusterOperationStatus_State ClusterOperationStatus::UNKNOWN;
const ClusterOperationStatus_State ClusterOperationStatus::PENDING;
const ClusterOperationStatus_State ClusterOperationStatus::RUNNING;
const ClusterOperationStatus_State ClusterOperationStatus::DONE;
const ClusterOperationStatus_State ClusterOperationStatus::State_MIN;
const ClusterOperationStatus_State ClusterOperationStatus::State_MAX;
const int ClusterOperationStatus::State_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void ClusterOperationStatus::InitAsDefaultInstance() {
  ::google::cloud::dataproc::v1beta2::_ClusterOperationStatus_default_instance_._instance.get_mutable()->state_start_time_ = const_cast< ::google::protobuf::Timestamp*>(
      ::google::protobuf::Timestamp::internal_default_instance());
}
void ClusterOperationStatus::clear_state_start_time() {
  if (GetArenaNoVirtual() == NULL && state_start_time_ != NULL) {
    delete state_start_time_;
  }
  state_start_time_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClusterOperationStatus::kStateFieldNumber;
const int ClusterOperationStatus::kInnerStateFieldNumber;
const int ClusterOperationStatus::kDetailsFieldNumber;
const int ClusterOperationStatus::kStateStartTimeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClusterOperationStatus::ClusterOperationStatus()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::scc_info_ClusterOperationStatus.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
}
ClusterOperationStatus::ClusterOperationStatus(const ClusterOperationStatus& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  inner_state_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.inner_state().size() > 0) {
    inner_state_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.inner_state_);
  }
  details_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.details().size() > 0) {
    details_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.details_);
  }
  if (from.has_state_start_time()) {
    state_start_time_ = new ::google::protobuf::Timestamp(*from.state_start_time_);
  } else {
    state_start_time_ = NULL;
  }
  state_ = from.state_;
  // @@protoc_insertion_point(copy_constructor:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
}

void ClusterOperationStatus::SharedCtor() {
  inner_state_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  details_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&state_start_time_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&state_) -
      reinterpret_cast<char*>(&state_start_time_)) + sizeof(state_));
}

ClusterOperationStatus::~ClusterOperationStatus() {
  // @@protoc_insertion_point(destructor:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  SharedDtor();
}

void ClusterOperationStatus::SharedDtor() {
  inner_state_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  details_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete state_start_time_;
}

void ClusterOperationStatus::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ClusterOperationStatus::descriptor() {
  ::protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClusterOperationStatus& ClusterOperationStatus::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::scc_info_ClusterOperationStatus.base);
  return *internal_default_instance();
}


void ClusterOperationStatus::Clear() {
// @@protoc_insertion_point(message_clear_start:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  inner_state_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  details_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && state_start_time_ != NULL) {
    delete state_start_time_;
  }
  state_start_time_ = NULL;
  state_ = 0;
  _internal_metadata_.Clear();
}

bool ClusterOperationStatus::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .google.cloud.dataproc.v1beta2.ClusterOperationStatus.State state = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_state(static_cast< ::google::cloud::dataproc::v1beta2::ClusterOperationStatus_State >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string inner_state = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_inner_state()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->inner_state().data(), static_cast<int>(this->inner_state().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.cloud.dataproc.v1beta2.ClusterOperationStatus.inner_state"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string details = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_details()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->details().data(), static_cast<int>(this->details().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.cloud.dataproc.v1beta2.ClusterOperationStatus.details"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.protobuf.Timestamp state_start_time = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_state_start_time()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  return false;
#undef DO_
}

void ClusterOperationStatus::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.cloud.dataproc.v1beta2.ClusterOperationStatus.State state = 1;
  if (this->state() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->state(), output);
  }

  // string inner_state = 2;
  if (this->inner_state().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->inner_state().data(), static_cast<int>(this->inner_state().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationStatus.inner_state");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->inner_state(), output);
  }

  // string details = 3;
  if (this->details().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->details().data(), static_cast<int>(this->details().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationStatus.details");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->details(), output);
  }

  // .google.protobuf.Timestamp state_start_time = 4;
  if (this->has_state_start_time()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->_internal_state_start_time(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
}

::google::protobuf::uint8* ClusterOperationStatus::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.cloud.dataproc.v1beta2.ClusterOperationStatus.State state = 1;
  if (this->state() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->state(), target);
  }

  // string inner_state = 2;
  if (this->inner_state().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->inner_state().data(), static_cast<int>(this->inner_state().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationStatus.inner_state");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->inner_state(), target);
  }

  // string details = 3;
  if (this->details().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->details().data(), static_cast<int>(this->details().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationStatus.details");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->details(), target);
  }

  // .google.protobuf.Timestamp state_start_time = 4;
  if (this->has_state_start_time()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->_internal_state_start_time(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  return target;
}

size_t ClusterOperationStatus::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string inner_state = 2;
  if (this->inner_state().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->inner_state());
  }

  // string details = 3;
  if (this->details().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->details());
  }

  // .google.protobuf.Timestamp state_start_time = 4;
  if (this->has_state_start_time()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *state_start_time_);
  }

  // .google.cloud.dataproc.v1beta2.ClusterOperationStatus.State state = 1;
  if (this->state() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->state());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClusterOperationStatus::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  GOOGLE_DCHECK_NE(&from, this);
  const ClusterOperationStatus* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClusterOperationStatus>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
    MergeFrom(*source);
  }
}

void ClusterOperationStatus::MergeFrom(const ClusterOperationStatus& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.inner_state().size() > 0) {

    inner_state_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.inner_state_);
  }
  if (from.details().size() > 0) {

    details_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.details_);
  }
  if (from.has_state_start_time()) {
    mutable_state_start_time()->::google::protobuf::Timestamp::MergeFrom(from.state_start_time());
  }
  if (from.state() != 0) {
    set_state(from.state());
  }
}

void ClusterOperationStatus::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClusterOperationStatus::CopyFrom(const ClusterOperationStatus& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.cloud.dataproc.v1beta2.ClusterOperationStatus)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClusterOperationStatus::IsInitialized() const {
  return true;
}

void ClusterOperationStatus::Swap(ClusterOperationStatus* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClusterOperationStatus::InternalSwap(ClusterOperationStatus* other) {
  using std::swap;
  inner_state_.Swap(&other->inner_state_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  details_.Swap(&other->details_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(state_start_time_, other->state_start_time_);
  swap(state_, other->state_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ClusterOperationStatus::GetMetadata() const {
  protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

ClusterOperationMetadata_LabelsEntry_DoNotUse::ClusterOperationMetadata_LabelsEntry_DoNotUse() {}
ClusterOperationMetadata_LabelsEntry_DoNotUse::ClusterOperationMetadata_LabelsEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void ClusterOperationMetadata_LabelsEntry_DoNotUse::MergeFrom(const ClusterOperationMetadata_LabelsEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata ClusterOperationMetadata_LabelsEntry_DoNotUse::GetMetadata() const {
  ::protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::file_level_metadata[1];
}
void ClusterOperationMetadata_LabelsEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void ClusterOperationMetadata::InitAsDefaultInstance() {
  ::google::cloud::dataproc::v1beta2::_ClusterOperationMetadata_default_instance_._instance.get_mutable()->status_ = const_cast< ::google::cloud::dataproc::v1beta2::ClusterOperationStatus*>(
      ::google::cloud::dataproc::v1beta2::ClusterOperationStatus::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ClusterOperationMetadata::kClusterNameFieldNumber;
const int ClusterOperationMetadata::kClusterUuidFieldNumber;
const int ClusterOperationMetadata::kStatusFieldNumber;
const int ClusterOperationMetadata::kStatusHistoryFieldNumber;
const int ClusterOperationMetadata::kOperationTypeFieldNumber;
const int ClusterOperationMetadata::kDescriptionFieldNumber;
const int ClusterOperationMetadata::kLabelsFieldNumber;
const int ClusterOperationMetadata::kWarningsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ClusterOperationMetadata::ClusterOperationMetadata()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::scc_info_ClusterOperationMetadata.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
}
ClusterOperationMetadata::ClusterOperationMetadata(const ClusterOperationMetadata& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      status_history_(from.status_history_),
      warnings_(from.warnings_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  labels_.MergeFrom(from.labels_);
  cluster_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.cluster_name().size() > 0) {
    cluster_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cluster_name_);
  }
  cluster_uuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.cluster_uuid().size() > 0) {
    cluster_uuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cluster_uuid_);
  }
  operation_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.operation_type().size() > 0) {
    operation_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operation_type_);
  }
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.description().size() > 0) {
    description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.description_);
  }
  if (from.has_status()) {
    status_ = new ::google::cloud::dataproc::v1beta2::ClusterOperationStatus(*from.status_);
  } else {
    status_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
}

void ClusterOperationMetadata::SharedCtor() {
  cluster_name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cluster_uuid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operation_type_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  status_ = NULL;
}

ClusterOperationMetadata::~ClusterOperationMetadata() {
  // @@protoc_insertion_point(destructor:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  SharedDtor();
}

void ClusterOperationMetadata::SharedDtor() {
  cluster_name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cluster_uuid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operation_type_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != internal_default_instance()) delete status_;
}

void ClusterOperationMetadata::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ClusterOperationMetadata::descriptor() {
  ::protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ClusterOperationMetadata& ClusterOperationMetadata::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::scc_info_ClusterOperationMetadata.base);
  return *internal_default_instance();
}


void ClusterOperationMetadata::Clear() {
// @@protoc_insertion_point(message_clear_start:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  status_history_.Clear();
  labels_.Clear();
  warnings_.Clear();
  cluster_name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  cluster_uuid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  operation_type_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (GetArenaNoVirtual() == NULL && status_ != NULL) {
    delete status_;
  }
  status_ = NULL;
  _internal_metadata_.Clear();
}

bool ClusterOperationMetadata::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string cluster_name = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cluster_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->cluster_name().data(), static_cast<int>(this->cluster_name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.cluster_name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string cluster_uuid = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(66u /* 66 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_cluster_uuid()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->cluster_uuid().data(), static_cast<int>(this->cluster_uuid().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.cluster_uuid"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .google.cloud.dataproc.v1beta2.ClusterOperationStatus status = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_status()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .google.cloud.dataproc.v1beta2.ClusterOperationStatus status_history = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_status_history()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string operation_type = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(90u /* 90 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_operation_type()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->operation_type().data(), static_cast<int>(this->operation_type().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.operation_type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string description = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u /* 98 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_description()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->description().data(), static_cast<int>(this->description().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.description"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, string> labels = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u /* 106 & 0xFF */)) {
          ClusterOperationMetadata_LabelsEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              ClusterOperationMetadata_LabelsEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&labels_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.LabelsEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.LabelsEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string warnings = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(114u /* 114 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_warnings()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->warnings(this->warnings_size() - 1).data(),
            static_cast<int>(this->warnings(this->warnings_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.warnings"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  return false;
#undef DO_
}

void ClusterOperationMetadata::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string cluster_name = 7;
  if (this->cluster_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cluster_name().data(), static_cast<int>(this->cluster_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.cluster_name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->cluster_name(), output);
  }

  // string cluster_uuid = 8;
  if (this->cluster_uuid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cluster_uuid().data(), static_cast<int>(this->cluster_uuid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.cluster_uuid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->cluster_uuid(), output);
  }

  // .google.cloud.dataproc.v1beta2.ClusterOperationStatus status = 9;
  if (this->has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      9, this->_internal_status(), output);
  }

  // repeated .google.cloud.dataproc.v1beta2.ClusterOperationStatus status_history = 10;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->status_history_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      10,
      this->status_history(static_cast<int>(i)),
      output);
  }

  // string operation_type = 11;
  if (this->operation_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operation_type().data(), static_cast<int>(this->operation_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.operation_type");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->operation_type(), output);
  }

  // string description = 12;
  if (this->description().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->description().data(), static_cast<int>(this->description().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.description");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->description(), output);
  }

  // map<string, string> labels = 13;
  if (!this->labels().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.LabelsEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.LabelsEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->labels().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->labels().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->labels().begin();
          it != this->labels().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<ClusterOperationMetadata_LabelsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(labels_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            13, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<ClusterOperationMetadata_LabelsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->labels().begin();
          it != this->labels().end(); ++it) {
        entry.reset(labels_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            13, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  // repeated string warnings = 14;
  for (int i = 0, n = this->warnings_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->warnings(i).data(), static_cast<int>(this->warnings(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.warnings");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      14, this->warnings(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
}

::google::protobuf::uint8* ClusterOperationMetadata::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string cluster_name = 7;
  if (this->cluster_name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cluster_name().data(), static_cast<int>(this->cluster_name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.cluster_name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->cluster_name(), target);
  }

  // string cluster_uuid = 8;
  if (this->cluster_uuid().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->cluster_uuid().data(), static_cast<int>(this->cluster_uuid().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.cluster_uuid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->cluster_uuid(), target);
  }

  // .google.cloud.dataproc.v1beta2.ClusterOperationStatus status = 9;
  if (this->has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        9, this->_internal_status(), deterministic, target);
  }

  // repeated .google.cloud.dataproc.v1beta2.ClusterOperationStatus status_history = 10;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->status_history_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        10, this->status_history(static_cast<int>(i)), deterministic, target);
  }

  // string operation_type = 11;
  if (this->operation_type().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->operation_type().data(), static_cast<int>(this->operation_type().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.operation_type");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->operation_type(), target);
  }

  // string description = 12;
  if (this->description().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->description().data(), static_cast<int>(this->description().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.description");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->description(), target);
  }

  // map<string, string> labels = 13;
  if (!this->labels().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.LabelsEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.LabelsEntry.value");
      }
    };

    if (deterministic &&
        this->labels().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->labels().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->labels().begin();
          it != this->labels().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<ClusterOperationMetadata_LabelsEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(labels_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       13, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<ClusterOperationMetadata_LabelsEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->labels().begin();
          it != this->labels().end(); ++it) {
        entry.reset(labels_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       13, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  // repeated string warnings = 14;
  for (int i = 0, n = this->warnings_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->warnings(i).data(), static_cast<int>(this->warnings(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.cloud.dataproc.v1beta2.ClusterOperationMetadata.warnings");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(14, this->warnings(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  return target;
}

size_t ClusterOperationMetadata::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .google.cloud.dataproc.v1beta2.ClusterOperationStatus status_history = 10;
  {
    unsigned int count = static_cast<unsigned int>(this->status_history_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->status_history(static_cast<int>(i)));
    }
  }

  // map<string, string> labels = 13;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->labels_size());
  {
    ::std::unique_ptr<ClusterOperationMetadata_LabelsEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->labels().begin();
        it != this->labels().end(); ++it) {
      entry.reset(labels_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  // repeated string warnings = 14;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->warnings_size());
  for (int i = 0, n = this->warnings_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->warnings(i));
  }

  // string cluster_name = 7;
  if (this->cluster_name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cluster_name());
  }

  // string cluster_uuid = 8;
  if (this->cluster_uuid().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->cluster_uuid());
  }

  // string operation_type = 11;
  if (this->operation_type().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->operation_type());
  }

  // string description = 12;
  if (this->description().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->description());
  }

  // .google.cloud.dataproc.v1beta2.ClusterOperationStatus status = 9;
  if (this->has_status()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *status_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ClusterOperationMetadata::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  GOOGLE_DCHECK_NE(&from, this);
  const ClusterOperationMetadata* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ClusterOperationMetadata>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
    MergeFrom(*source);
  }
}

void ClusterOperationMetadata::MergeFrom(const ClusterOperationMetadata& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  status_history_.MergeFrom(from.status_history_);
  labels_.MergeFrom(from.labels_);
  warnings_.MergeFrom(from.warnings_);
  if (from.cluster_name().size() > 0) {

    cluster_name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cluster_name_);
  }
  if (from.cluster_uuid().size() > 0) {

    cluster_uuid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.cluster_uuid_);
  }
  if (from.operation_type().size() > 0) {

    operation_type_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.operation_type_);
  }
  if (from.description().size() > 0) {

    description_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.description_);
  }
  if (from.has_status()) {
    mutable_status()->::google::cloud::dataproc::v1beta2::ClusterOperationStatus::MergeFrom(from.status());
  }
}

void ClusterOperationMetadata::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ClusterOperationMetadata::CopyFrom(const ClusterOperationMetadata& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.cloud.dataproc.v1beta2.ClusterOperationMetadata)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ClusterOperationMetadata::IsInitialized() const {
  return true;
}

void ClusterOperationMetadata::Swap(ClusterOperationMetadata* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ClusterOperationMetadata::InternalSwap(ClusterOperationMetadata* other) {
  using std::swap;
  CastToBase(&status_history_)->InternalSwap(CastToBase(&other->status_history_));
  labels_.Swap(&other->labels_);
  warnings_.InternalSwap(CastToBase(&other->warnings_));
  cluster_name_.Swap(&other->cluster_name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  cluster_uuid_.Swap(&other->cluster_uuid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  operation_type_.Swap(&other->operation_type_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  description_.Swap(&other->description_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(status_, other->status_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ClusterOperationMetadata::GetMetadata() const {
  protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_google_2fcloud_2fdataproc_2fv1beta2_2foperations_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace v1beta2
}  // namespace dataproc
}  // namespace cloud
}  // namespace google
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::cloud::dataproc::v1beta2::ClusterOperationStatus* Arena::CreateMaybeMessage< ::google::cloud::dataproc::v1beta2::ClusterOperationStatus >(Arena* arena) {
  return Arena::CreateInternal< ::google::cloud::dataproc::v1beta2::ClusterOperationStatus >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::cloud::dataproc::v1beta2::ClusterOperationMetadata_LabelsEntry_DoNotUse* Arena::CreateMaybeMessage< ::google::cloud::dataproc::v1beta2::ClusterOperationMetadata_LabelsEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::google::cloud::dataproc::v1beta2::ClusterOperationMetadata_LabelsEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::cloud::dataproc::v1beta2::ClusterOperationMetadata* Arena::CreateMaybeMessage< ::google::cloud::dataproc::v1beta2::ClusterOperationMetadata >(Arena* arena) {
  return Arena::CreateInternal< ::google::cloud::dataproc::v1beta2::ClusterOperationMetadata >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
