// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: google/cloud/dialogflow/v2/session.proto

#include "google/cloud/dialogflow/v2/session.pb.h"
#include "google/cloud/dialogflow/v2/session.grpc.pb.h"

#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace google {
namespace cloud {
namespace dialogflow {
namespace v2 {

static const char* Sessions_method_names[] = {
  "/google.cloud.dialogflow.v2.Sessions/DetectIntent",
  "/google.cloud.dialogflow.v2.Sessions/StreamingDetectIntent",
};

std::unique_ptr< Sessions::Stub> Sessions::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Sessions::Stub> stub(new Sessions::Stub(channel));
  return stub;
}

Sessions::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_DetectIntent_(Sessions_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_StreamingDetectIntent_(Sessions_method_names[1], ::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::Status Sessions::Stub::DetectIntent(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DetectIntentRequest& request, ::google::cloud::dialogflow::v2::DetectIntentResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_DetectIntent_, context, request, response);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::DetectIntentResponse>* Sessions::Stub::AsyncDetectIntentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DetectIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2::DetectIntentResponse>::Create(channel_.get(), cq, rpcmethod_DetectIntent_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::google::cloud::dialogflow::v2::DetectIntentResponse>* Sessions::Stub::PrepareAsyncDetectIntentRaw(::grpc::ClientContext* context, const ::google::cloud::dialogflow::v2::DetectIntentRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::google::cloud::dialogflow::v2::DetectIntentResponse>::Create(channel_.get(), cq, rpcmethod_DetectIntent_, context, request, false);
}

::grpc::ClientReaderWriter< ::google::cloud::dialogflow::v2::StreamingDetectIntentRequest, ::google::cloud::dialogflow::v2::StreamingDetectIntentResponse>* Sessions::Stub::StreamingDetectIntentRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::google::cloud::dialogflow::v2::StreamingDetectIntentRequest, ::google::cloud::dialogflow::v2::StreamingDetectIntentResponse>::Create(channel_.get(), rpcmethod_StreamingDetectIntent_, context);
}

::grpc::ClientAsyncReaderWriter< ::google::cloud::dialogflow::v2::StreamingDetectIntentRequest, ::google::cloud::dialogflow::v2::StreamingDetectIntentResponse>* Sessions::Stub::AsyncStreamingDetectIntentRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::google::cloud::dialogflow::v2::StreamingDetectIntentRequest, ::google::cloud::dialogflow::v2::StreamingDetectIntentResponse>::Create(channel_.get(), cq, rpcmethod_StreamingDetectIntent_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::google::cloud::dialogflow::v2::StreamingDetectIntentRequest, ::google::cloud::dialogflow::v2::StreamingDetectIntentResponse>* Sessions::Stub::PrepareAsyncStreamingDetectIntentRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::google::cloud::dialogflow::v2::StreamingDetectIntentRequest, ::google::cloud::dialogflow::v2::StreamingDetectIntentResponse>::Create(channel_.get(), cq, rpcmethod_StreamingDetectIntent_, context, false, nullptr);
}

Sessions::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Sessions_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Sessions::Service, ::google::cloud::dialogflow::v2::DetectIntentRequest, ::google::cloud::dialogflow::v2::DetectIntentResponse>(
          std::mem_fn(&Sessions::Service::DetectIntent), this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Sessions_method_names[1],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Sessions::Service, ::google::cloud::dialogflow::v2::StreamingDetectIntentRequest, ::google::cloud::dialogflow::v2::StreamingDetectIntentResponse>(
          std::mem_fn(&Sessions::Service::StreamingDetectIntent), this)));
}

Sessions::Service::~Service() {
}

::grpc::Status Sessions::Service::DetectIntent(::grpc::ServerContext* context, const ::google::cloud::dialogflow::v2::DetectIntentRequest* request, ::google::cloud::dialogflow::v2::DetectIntentResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Sessions::Service::StreamingDetectIntent(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::google::cloud::dialogflow::v2::StreamingDetectIntentResponse, ::google::cloud::dialogflow::v2::StreamingDetectIntentRequest>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace google
}  // namespace cloud
}  // namespace dialogflow
}  // namespace v2

